### ISSUE TITLE
点击画中画 按钮 没有反应 ？

### ISSUE THREAD

**Issue by 12207480** [jakajacky/ZVideoView#1]
点击画中画 按钮 没有反应 ？这是怎么了

**Comment by jakajacky** [comment]
设备支持画中画吗？我写的时候没判断当前设备是否支持画中画，所以可能是这个问题吧？我目前用的是pad ari，9.2，是可以的

**Comment by jakajacky** [comment]
@12207480 设备支持画中画吗？我写的时候没判断当前设备是否支持画中画，所以可能是这个问题吧？我目前用的是pad air，9.2，是可以的

**Comment by 12207480** [comment]
哦 谢谢提醒
